default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: programming-the-city-development

test:
  <<: *default
  database: programming-the-city-test

production:
  <<: *default
  database: programming-the-city-production
